function orgt(s) {
  return binl2hex(core_hx(str2binl(s), s.length * chrsz));
}
var bookConfig = {
  CreatedBy: "",
  CreatedTime: "",
  CreatedVersion: "",
  productName: "Javier Sanchez Mendoza",
  productVersion: "4.11.11",
  homePage: "https://www.javier1nc.com",
  totalPageCount: 12,
  largePageWidth: 989,
  largePageHeight: 1280,
  BookTemplateName: "Metro",
  BookThemeName: "Default",
  SlideshowAutoPlay: false,
  SlideshowPlayInterval: 5,
  language: "",
  AboutAddress: "",
  AboutEmail: "",
  AboutMobile: "",
  AboutWebsite: "",
  AboutDescription: "",
  AboutAuthor: "",
  searchPositionJS: "files/search/text_position[%d].js",
  normalPath: "files/page/",
  largePath: "files/page/",
  thumbPath: "files/thumb/",
  isHasPdf: 1,
  canvasRender: false,
  flipshortcutbutton: "Show",
  phoneFlipShortcutButton: false,
  appLogoIcon: "files/extfile/appLogoIcon.png",
  appLogoLinkURL: "",
  logoPadding: "0",
  logoHeight: "40",
  bgBeginColor: "#505050",
  bgEndColor: "#505050",
  bgMRotation: 30,
  backGroundImgURL: "",
  backgroundPosition: "Stretch",
  backgroundOpacity: "100",
  backgroundScene: "None",
  BackgroundSoundButtonVisible: "Show",
  FlipSound: "Yes",
  BackgroundSoundURL: "",
  BackgroundSoundLoop: "-1",
  bgSoundVol: "50",
  loadingCaption: "",
  loadingCaptionFontSize: "20",
  loadingCaptionColor: "#DDDDDD",
  loadingPicture: "",
  loadingPictureHeight: "150",
  loadingBackground: "#323232",
  showLoadingGif: "Yes",
  loadingDisplayTime: "0",
  loadingVideo: "",
  ToolBarVisible: "Yes",
  toolbarColor: "#333333",
  iconColor: "#EEEEEE",
  iconFontColor: "#EEEEEE",
  formFontColor: "#EEEEEE",
  formBackgroundColor: "#3963A5",
  ToolBarAlpha: 0.8,
  HomeButtonVisible: false,
  HomeURL: "%1%",
  aboutButtonVisible: false,
  aboutContactInfoTxt: "",
  enablePageBack: "Hide",
  ShareButtonVisible: true,
  addCurrentPage: false,
  ThumbnailsButtonVisible: true,
  ThumbnailSize: "small",
  BookMarkButtonVisible: false,
  TableOfContentButtonVisible: "Show",
  isHideTabelOfContentNodes: "yes",
  SearchButtonVisible: "Show",
  leastSearchChar: "2",
  searchKeywordFontColor: "#FFB000",
  searchHightlightColor: "#FDC606",
  SelectTextButtonVisible: false,
  WeChatShareButtonVisible: false,
  WeChatShareButtonIcon: "",
  OnlyOpenInWechat: false,
  NoWechatSharing: false,
  PrintButtonVisible: false,
  printWatermarkFile: "",
  AutoPlayButtonVisible: "Show",
  autoPlayAutoStart: false,
  autoPlayDuration: "3",
  autoPlayLoopCount: "1",
  DownloadButtonVisible: false,
  downloadConfig: "",
  PhoneButtonVisible: "Hide",
  PhoneButtonIcon: "",
  PhoneNumbers: "",
  ZoomButtonVisible: true,
  SupportOperatePageZoom: "Yes",
  middleZoomWidth: "0",
  mouseWheelFlip: "yes",
  ZoomMapVisible: "Hide",
  EmailButtonVisible: false,
  btnShareWithEmailSubject: "",
  btnShareWithEmailBody: "{link}",
  MagnifierButtonVisible: "Hide",
  FullscreenButtonVisible: "Show",
  AnnotationButtonVisible: false,
  showGotoButtonsAtFirst: false,
  buttonsSortXML: [
    "thumb",
    "table",
    "goto",
    "zoom",
    "bookmark",
    "number",
    "sound",
    "search",
    "print",
    "annotation",
    "wechat",
    "email",
    "btnshare",
    "download",
    "language",
    "home",
    "autoflip",
    "select",
    "about",
    "report",
    "doublesinglepage",
  ],
  QRCode: false,
  LeftShadowWidth: 0,
  LeftShadowAlpha: "1",
  RightShadowWidth: 0,
  RightShadowAlpha: "1",
  ShowTopLeftShadow: false,
  pageHighlightType: "book",
  HardPageEnable: false,
  hardCoverBorderWidth: "8",
  borderColor: "#572F0D",
  cornerRound: "8",
  outerCoverBorder: "Yes",
  pageBackgroundColor: "#FFFFFF",
  BindingType: "side",
  thicknessWidthType: "thick",
  bookPageStretch: false,
  thicknessColor: "#FFFFFF",
  textClarityEnhancement: "0",
  totalPagesCaption: "",
  pageNumberCaption: "",
  hideMiniFullscreen: false,
  maxWidthToSmallMode: "400",
  maxHeightToSmallMode: "350",
  FlipStyle: "Flip",
  FlipDirection: "0",
  supportSerialsFlip: false,
  flippingTime: "0.3",
  RightToLeft: false,
  isTheBookOpen: false,
  SingleModeBanFlipToLastPage: false,
  showThicknessOnMobile: false,
  autoDoublePage: "auto",
  DoubleSinglePageButtonVisible: false,
  topMargin: 10,
  bottomMargin: 10,
  leftMargin: 10,
  rightMargin: 10,
  retainBookCenter: "Yes",
  isSingleBookFullWindowOnMobile: false,
  topMarginOnMobile: "0",
  bottomMarginOnMobile: "0",
  leftMarginOnMobile: "0",
  rightMarginOnMobile: "0",
  toolbarAlwaysShow: false,
  showHelpContentAtFirst: false,
  InstructionsButtonVisible: "Show",
  showBookInstructionOnStart: false,
  showInstructionOnStart: false,
  CurlingPageCorner: "Yes",
  leftRightPnlShowOption: "None",
  restorePageVisible: false,
  appLargeLogoIcon: "",
  appLargeLogoURL: "",
  LargeLogoPosition: "top-left",
  isFixLogoSize: false,
  logoFixWidth: "0",
  logoFixHeight: "0",
  isStopMouseMenu: "yes",
  useTheAliCloudChart: false,
  highDefinitionConversion: false,
  updateURLForPage: false,
  googleAnalyticsID: "",
  OnlyOpenInIframe: "No",
  OnlyOpenInIframeInfo: "No reading rights",
  OpenWindow: "Blank",
  showLinkHint: "No",
  shotPic: "",
  bookTitle: "FLIPBOOK",
  pageNumColor: "#1B2930",
  thumbnailColor: "#333333",
  thumbnailAlpha: 70,
  randomString: "ZwFUPYZGJjcjj1DX",
  securityType: 1,
  singlePasswordMD5: "",
  singlePasswordKey: "",
  excludeFrontPages: "0",
  passwardPrompt: "",
  isShowAssistantPerson: true,
  mainPDF: "files/pg3d.pdf",
};
var language = [];
var fliphtml5_pages = [
  { l: "files/page/1.jpg", t: "files/thumb/1.jpg" },
  { l: "files/page/2.jpg", t: "files/thumb/2.jpg" },
  { l: "files/page/3.jpg", t: "files/thumb/3.jpg" },
  { l: "files/page/4.jpg", t: "files/thumb/4.jpg" },
  { l: "files/page/5.jpg", t: "files/thumb/5.jpg" },
  { l: "files/page/6.jpg", t: "files/thumb/6.jpg" },
  { l: "files/page/7.jpg", t: "files/thumb/7.jpg" },
  { l: "files/page/8.jpg", t: "files/thumb/8.jpg" },
  { l: "files/page/9.jpg", t: "files/thumb/9.jpg" },
  { l: "files/page/10.jpg", t: "files/thumb/10.jpg" },
  { l: "files/page/11.jpg", t: "files/thumb/11.jpg" },
  { l: "files/page/12.jpg", t: "files/thumb/12.jpg" },
];
var ols = [
  {
    caption: "¿Qué es ProGeo3D?",
    url: "",
    page: "5",
    level: "1",
    children: [
      {
        caption: "La geometría visual",
        url: "",
        page: "5",
        level: "2",
        children: [],
      },
      {
        caption: "Armonía, cuartetas armónicas y curvas armónicas",
        url: "",
        page: "5",
        level: "2",
        children: [],
      },
      {
        caption: "Autoría de unidades didácticas",
        url: "",
        page: "6",
        level: "2",
        children: [],
      },
      {
        caption: "Sobre la presente documentación",
        url: "",
        page: "6",
        level: "2",
        children: [],
      },
    ],
  },
  {
    caption: "Barras de controles en ProGeo3D",
    url: "",
    page: "9",
    level: "1",
    children: [
      {
        caption: "La barra horizontal superior",
        url: "",
        page: "9",
        level: "2",
        children: [],
      },
      {
        caption: "La barra de constructores geométricos",
        url: "",
        page: "11",
        level: "2",
        children: [],
      },
      {
        caption: "Constructores geométricos en 3D",
        url: "",
        page: "32",
        level: "2",
        children: [],
      },
      {
        caption: "La barra horizontal inferior",
        url: "",
        page: "42",
        level: "2",
        children: [],
      },
      {
        caption: "Controles contenidos en el área de visualización",
        url: "",
        page: "47",
        level: "2",
        children: [],
      },
      {
        caption: "Miscelánea sobre la exploración y selección de objetos",
        url: "",
        page: "54",
        level: "2",
        children: [],
      },
      {
        caption: "Presentaciones paso a paso con sus textos",
        url: "",
        page: "55",
        level: "2",
        children: [
          {
            caption: "Los elementos del panel de edición",
            url: "",
            page: "56",
            level: "3",
            children: [],
          },
          {
            caption: "Introducción de texto enriquecido",
            url: "",
            page: "59",
            level: "3",
            children: [],
          },
          {
            caption: "Separación del texto en columnas",
            url: "",
            page: "61",
            level: "3",
            children: [],
          },
        ],
      },
    ],
  },
  {
    caption: "Guardado y recuperación de archivos",
    url: "",
    page: "63",
    level: "1",
    children: [
      {
        caption: "Los archivos de páginas",
        url: "",
        page: "63",
        level: "2",
        children: [
          {
            caption: "Contenido de los archivos de página",
            url: "",
            page: "64",
            level: "3",
            children: [],
          },
          {
            caption:
              "Tipos de objetos gráficos dentro de CONSTRUCTION en el archivo de aplicación",
            url: "",
            page: "69",
            level: "3",
            children: [],
          },
          {
            caption: "Código en la cola de cada renglón en CONSTRUCTION",
            url: "",
            page: "81",
            level: "3",
            children: [],
          },
          {
            caption: "Los nombres de los colores",
            url: "",
            page: "82",
            level: "3",
            children: [],
          },
        ],
      },
      {
        caption: "Objetos gráficos principales y asociados",
        url: "",
        page: "82",
        level: "2",
        children: [],
      },
    ],
  },
  {
    caption: "Contenido de ProGeo3D",
    url: "",
    page: "85",
    level: "1",
    children: [
      {
        caption: "La herramienta como tal",
        url: "",
        page: "85",
        level: "2",
        children: [],
      },
      {
        caption: "El papel de DescartesJS",
        url: "",
        page: "85",
        level: "2",
        children: [],
      },
      {
        caption: "Sugerencias de uso",
        url: "",
        page: "85",
        level: "2",
        children: [
          {
            caption: "ProGeo3D en un navegador",
            url: "",
            page: "86",
            level: "3",
            children: [],
          },
          {
            caption: "ProGeo3D desde DescartesJS",
            url: "",
            page: "86",
            level: "3",
            children: [],
          },
        ],
      },
      {
        caption: "Los archivos asociados de ProGeo3D",
        url: "",
        page: "86",
        level: "2",
        children: [
          {
            caption: "Los archivos en raíz",
            url: "",
            page: "86",
            level: "3",
            children: [],
          },
          {
            caption: "Los archivos de motor",
            url: "",
            page: "87",
            level: "3",
            children: [],
          },
          {
            caption: "Los íconos",
            url: "",
            page: "87",
            level: "3",
            children: [],
          },
          {
            caption: "Las imágenes",
            url: "",
            page: "87",
            level: "3",
            children: [],
          },
          {
            caption: "La librería",
            url: "",
            page: "88",
            level: "3",
            children: [],
          },
          {
            caption: "Los logos",
            url: "",
            page: "88",
            level: "3",
            children: [],
          },
          {
            caption: "El teclado",
            url: "",
            page: "88",
            level: "3",
            children: [],
          },
          {
            caption: "Los macros",
            url: "",
            page: "90",
            level: "3",
            children: [],
          },
          {
            caption: "Las carpetas de libros",
            url: "",
            page: "90",
            level: "3",
            children: [],
          },
        ],
      },
      {
        caption: "Diversos usos del archivo index.html",
        url: "",
        page: "90",
        level: "2",
        children: [],
      },
    ],
  },
];
var bmtConfig = { tabs: [], hasTexture: false, onSideEdge: false };
var staticAd = {
  haveAd: false,
  adPosition: 0,
  adHeight: 60,
  interval: 3000,
  data: [],
};
var videoList = [];
var slideshow = [];
var flipByAudio = { audioType: 0, audioFile: "", showPlayer: false, items: [] };
var phoneNumber = [];
var bookPlugin = null;
var userList = {};
var search_pages = [
  { index: 0 },
  { index: 1 },
  { index: 2 },
  { index: 3 },
  { index: 4 },
  { index: 5 },
  { index: 6 },
  { index: 7 },
  { index: 8 },
  { index: 9 },
  { index: 10 },
  { index: 11 },
];
var downloadconfig = {
  pdf: { isOriginPath: true, url: "", urlOnlink: "" },
  isDownloadProject: false,
  isDownloadAttach: false,
  attachments: [],
};
